apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-rwx
  name: nginx-rwx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-rwx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-rwx
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: "/var/www/html"
          name: mypd
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: pvc-rwx
status: {}
