apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-rwo-2
  name: nginx-rwo-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rwo-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-rwo-2
    spec:
      nodeName: cnpwkpr82.dc2.true.th
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: "/var/www/html"
          name: mypd
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: pvc-rwo-2
status: {}
