apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rwo-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: ontap-san
