apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-version-2
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: nginx-sts-2 # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-sts-2 # has to match .spec.selector.matchLabels
    spec:
      nodeName: k8swkbnats6.tdev.true.th
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - nginx-sts-2
      #       topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: MESSAGE
          value: "hello world"
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(MESSAGE) >> /usr/share/nginx/html/pump-test.txt; sleep 10;done" ]
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ontap-san"
      resources:
        requests:
          storage: 1Gi
